### ISSUE TITLE
Query Parameters using the same name and group; second property/operation ignored

### ISSUE THREAD

**Issue by AlexThurston** [usnistgov/ACVP#895]
**environment**
Demo

**testSessionId**
N/A

**vsId**
N/A

**Algorithm registration**
N/A

**Endpoint in which the error is experienced**
`https://demo.acvts.nist.gov/acvp/v1/vendors?name[0]=contains:inc&name[0]=contains:acme` GET

**Expected behaviour**
According to the documentation for how query parameters work, elements of the same group will be **AND**'d together.
https://htmlpreview.github.io/?https://github.com/usnistgov/ACVP/blob/master/artifacts/draft-fussell-acvp-spec-00.html#rfc.section.11.6

In my above query, I would have expected that it would return to me only vendors whose name contain the word `inc` **AND** `acme`.

However, what it looks like it's doing is ignoring my second argument.  I'm going to go out on a limb and guess that the reason is because they are the same property.  If I filter on two different properties in the same group, this does appear to work correctly.

**Comment by shaneshaffer** [comment]
Yes, that's the issue. The way the querystring is being handled, through a property of the platform's HttpRequest object, produces a collection of key-value pairs. Since there are duplicate keys, only one value is included. This seems to be a fairly common behavior across multiple platforms, yet I can find nothing in any specification documents (HTTP, etc.) which say whether or not the same parameter should be allowed to appear multiple times in the same querystring. Of course, if it isn't allowed, then there wouldn't be a way to do the query you're wanting to do, at least not with the syntax we have for these querystrings (which is already pretty nasty).

To make this work, it seems like we'll have to parse the querystring manually to allow duplicate parameter names.

**Comment by AlexThurston** [comment]
I've got another situation/question related to how querying is handled.  Let's say i wanted to find all the people in ACVP where the email contains something (**@acme.com**, for example).  I would have expected that a query string of `emails[0]=contains:@acme.com` would work, but it doesn't seem to.  I'm guessing this because in the model, emails is an array and the querying either doesn't allow for it, or there is more syntax that needs to be added by me.

As an aside (and since you mentioned that the query syntax is nasty), ElasticSearch provides a really nice Lucene DB for being able to search through documents like how many of the resources appear to be stored.  It seems like the current query syntax is a little less flexible than it could be.  I am likely in the minority as far as how people the API, but like I said, I thought it was worth mentioning.

**Comment by shaneshaffer** [comment]
That should be `email[0]=contains:@acme.com`, no "s". I don't know if it was intentional or not that what the spec lists as the available query parameters are slightly different from the names in the JSON.

FWIW, I completely rewrote our handling of these queries yesterday, so hopefully they'll all be a lot faster once we get that tested and deployed. After initially fixing your original issue I noticed how sensitive the performance was to the order and specificity of the search terms - searching for "inc AND acme" would time out, while "acme AND inc" was acceptable. That shouldn't be an issue in the new approach.

At least for now we're stuck with what the spec says for the query syntax. There are definitely some things that one can't do with that syntax, and trying to express the query through a RESTful GET seems to limit our options for that syntax a bit. Perhaps we can reconsider for a future version of the spec.

**Comment by AlexThurston** [comment]
> That should be email[0]=contains:@acme.com, no "s". I don't know if it was intentional or not that what the spec lists as the available query parameters are slightly different from the names in the JSON.

Bah, that's my bad.  I should have looked at the API spec.  I guess I just assumed that the property would match the JSON even thought he documentation does specify that they are not the same.  That is a bit unintuitive, but maybe it was intentional.

I've got another weird thing in this area.  
The following works:
**GET** `https://demo.acvts.nist.gov/acvp/v1/persons?email[0]=contains:@acme`

The following gives me a 500:
**GET** `https://demo.acvts.nist.gov/acvp/v1/persons?email[0]=contains:@lightship`

```json
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Internal service error. Contact service provider."
  }
]
```

Maybe this is the same root cause as https://github.com/usnistgov/ACVP/issues/899

**Comment by shaneshaffer** [comment]
It is the same root cause - the vendor_url is required on a Person create (though the spec doesn't say so), and we weren't validating that properly, which led to some people being created without an organization. That then leads to this error in something that isn't expecting a null there.

I've updated that one Person record to point to one of the Lightship organizations (there are 3), so that query should work now.

**Comment by celic** [comment]
Can this be closed?

**Comment by AlexThurston** [comment]
It depends, I believe the root issue that you can't `AND` or `OR` a search on the same field still exists.  @shaneshaffer explained that it is a limitation of the internal tooling.  I'd say that it's something that people might want to be able to do.  Perhaps just adding to the documentation of the query parameters structure that you cannot perform the boolean logic on the same field in a single query would be a resolution, but either way I kinda feel like some sort of change is warranted to avoid people raising this as an issue again.

**Comment by dmchodnicki** [comment]
The original issue of the AND search not working for the second property within the same name/group was resolved by Shane's query rewrite back in mid-June.  Vendor and Module AND query tests were re-run to confirm the desired  functionality.
